CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  method VARCHAR(20) NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  currency VARCHAR(5) NOT NULL DEFAULT 'EUR',
  status VARCHAR(20) NOT NULL,
  detail TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);
